### ISSUE TITLE
Disabling Background Color

### ISSUE THREAD

**Issue by h3x4g0ns** [abishekvashok/cmatrix#146]
Is it possible to disable to background color when `cmatrix` runs? I have a color theme applied in the terminal so when `cmatrix` runs, there's a gray background underneath.

![Screenshot_2022-04-21-05-59-22_3440x1440](https://user-images.githubusercontent.com/28676754/164576261-e83e1a7e-e05b-4ffa-9d25-e118a45bb8af.png)

**Comment by abishekvashok** [comment]
Can you try building with `make` and using code from the development branch please?

**Comment by nikoof** [comment]
It seems the background color depends on whether use_default_colors is used. And that depends on whether HAVE_USE_DEFAULT_COLORS is defined, which the autoconf script does, but not the CMakeLists.txt file, so I figure that the package you're using was configured with cmake and that's why it's missing this feature.

Checking for the function and defining that macro in the cmake script should solve it.

**Comment by lilly-lizard** [comment]
just tried building this with default autoconf config and there's no background which is great! just a fyi in case this could be closed.

**Comment by abishekvashok** [comment]
Yes, I think it works via autotools and doesn't work with cmake. I think we could use the commit authored by @Nikoof on his fork. @Nikoof would you like to make a pr from your fork?

**Comment by nikoof** [comment]
Will do!

**Comment by abishekvashok** [comment]
Seems like #168 closes this, let me know if it doesn't :)
