### ISSUE TITLE
hang and start cmatrix

### ISSUE THREAD

**Issue by RanchoCooper** [abishekvashok/cmatrix#2]
I wanna start cmatrix as screen-bakeground when leaving computer, how can I make it?

**Comment by llabhishekll** [comment]
In which platform Linux/Windows ?

**Comment by RanchoCooper** [comment]
Linux, my temporary way was set a shortcuts run `cmatrix` with terminal's arguments '--full-screen'

but it's not safe enought, any key-input will enter my desktop without passwd

I wanna be safe, with enter passwd

**Comment by abishekvashok** [comment]
> leaving computer

Do you mean shutting it down or in sleep as a  screen saver?
@RanchoCooper

**Comment by livibetter** [comment]
Since @pipeseroni got me, I have been trying to find a way to do something like this, a way that you can actually have a *terminal screensaver* using any programs that draw stuff in terminal window.

I was thinking someone might have written a special terminal emulator that also works as screen locker, like a merged program of st + xlock's locking, but I couldn't find one.  Or a locker that can grab all the inputs, and leave X's screen as is, then when any inputs come in, popping up a dialog, but no such thing exists.  I wonder if we can simply hack xlock for its password input screen.

----

When I read @RanchoCooper's words a few hours ago:

> any key-input will enter my desktop

A *terribly bad* idea came to me: **what if that triggers lock screen?**

It's not perfect, because once entering the lock screen, we stay with it, but it's an idea, although a crappy one.  Nonetheless, I was wondering if I could somehow achieve it only using simple shell script without any library/tool to interact with X.

So I wrote this script:

```bash
#!/bin/bash

# monitor any input device plugging in and unplugging
ICMD="ls /dev/input/by-id/"
ILST="$($ICMD)"
# () to suppress job control message
( while [[ "$($ICMD)" == "$ILST" ]]; do sleep 0.1; done & )

# monitor all inputs
# note: PS/2 won't be in by-*/*, so listening to all input*
for i in /dev/input/event*; do
    # just read one byte and exits.
    # when unplugging an input device, cat throws "No such device" to stderr
    cat "$i" 2>/dev/null | read -n 1 &
done

# wait here until any job exits
wait -n

# kill all the remaining jobs
kill $(jobs -p)

su -c xlock $SUDO_USER
```

Unfortunately, this has to be run by root, if using tools like xinput or any that can listen to whole X, it doesn't require root.  Also, you don't want any power saving with this script, or maybe let mouse input passes, so it can bring computer out of saving mode without triggering lock screen, if switching windows can't be done with mouse.

Anyway, any sane people wouldn't want to use this, I am just throwing the script here for insane people who like insecure stuff.
