### ISSUE TITLE
curses.h is not found

### ISSUE THREAD

**Issue by ZoeSj** [abishekvashok/cmatrix#56]
I am submitting a 

### Problem or Feature in Brief

```
gcc -DHAVE_CONFIG_H -I. -I. -I.     -g -O2 -Wall -Wno-comment -c cmatrix.c
cmatrix.c:37:20: fatal error: curses.h: No such file or directory
 #include <curses.h>
                    ^
compilation terminated
```
###

**Comment by abishekvashok** [comment]
Didn't you run `./configure`?
You must have got an error there.

It is because you don't have ncurses. cmatrix depends on ncurses and needs it to work. You could try to install it by using a package manager present in your distribution.

On a Debian machine:
`apt-get install libncurses5-dev`

On a redhat derivative such as fedora:
`yum install libncurses5-dev`

Or, you could download the source and try to compile it yourself.

Cheers
