### ISSUE TITLE
cmatrix forces solarized dark background

### ISSUE THREAD

**Issue by teyter** [abishekvashok/cmatrix#83]
I am submitting a 

### Problem or Feature in Brief

https://imgur.com/V5sLDCr

As you can see in the image, it appears that cmatrix is forcing a Solarized dark-type background in my terminal. This was not like this before. It would just appear normally on my "tango-colorscheme" background. I have no idea why this is happening.

**Comment by incomingstick** [comment]
I am experiencing this same issue. It appears that cmatrix has started using a background color, specifically the color set to my color0 "black".

Here is how know what termcolor is the culprit (top is my normal color, bottom is changing the value):
![2019-06-07-16:56:46](https://user-images.githubusercontent.com/11799068/59135714-9958e780-8945-11e9-8a5f-56a23995efea.png)

![2019-06-07-16:58:37](https://user-images.githubusercontent.com/11799068/59135715-9c53d800-8945-11e9-997f-199f0cddb179.png)

Is there a way to have cmatrix not add a BG color, and instead use the terminals opaque background?

**Comment by abishekvashok** [comment]
I would get back on this

**Comment by incomingstick** [comment]
I did some testing to try and hunt down the change that introduced the background color, as it is not present in the v1.2 release, compared to v2.0

I have been able to determine it was introduced somewhere between 6525abe and 9fffb25, with 9fffb25 being the most likely culprit. I have been unable to determine the exact cause, but I wanted to share what I have found thus far.

**Comment by incomingstick** [comment]
I have made more progress here. It is actually an issue when building with CMake specifically. I just did a manual autotools build with the current master branch, and it is NOT adding a background color:

![image](https://user-images.githubusercontent.com/11799068/59530262-c3ac2700-8ea8-11e9-8f2b-3a09cb67d722.png)

and here is the master branch built using CMake (built in a separate `build/` directory to avoid conflicting with the previously built binary):

![image](https://user-images.githubusercontent.com/11799068/59531899-d7598c80-8eac-11e9-8111-333433798da6.png)

Edit: Taking this one step further, I am now able to determine it is because the CMake build **does not** use `config.h`. When you disable "add_definitions(-DEXCLUDE_CONFIG_H)" (line 15 of CMakeLists.txt), and use the `config.h` made from running `./configure`  it does not add the background color:

![image](https://user-images.githubusercontent.com/11799068/59532962-c3635a00-8eaf-11e9-9ffd-e9481b66480e.png)

I will be attempting to provide a possible solution with a PR soon.

**Comment by 0ceanlight** [comment]
I'm still having this same issue... I'm on Arch with BSPWM

**Comment by abishekvashok** [comment]
@0ceanlight will you be able to give little more specifics, for example the version you used! It would also be really helpful if I can get some steps to replicate this :)

**Comment by incomingstick** [comment]
> I'm still having this same issue... I'm on Arch with BSPWM

Are you installing via the AUR? This issue will still be present unless you build manually. The AUR build needs to be updated with my fix to the CMAKE build.
